// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScheduleServiceDatabaseImplement;

#nullable disable

namespace ScheduleServiceDatabaseImplement.Migrations
{
    [DbContext(typeof(ScheduleServiceDatabase))]
    [Migration("20260406153744_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ScheduleServiceDatabaseImplement.Models.DutyPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Position")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("duty_persons", null, t =>
                        {
                            t.HasComment("Дежурные");
                        });
                });

            modelBuilder.Entity("ScheduleServiceDatabaseImplement.Models.DutySchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DutyPersonId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("interval");

                    b.Property<int?>("LessonTimeId")
                        .HasColumnType("integer");

                    b.Property<string>("Place")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("DutyPersonId");

                    b.HasIndex("LessonTimeId");

                    b.ToTable("duty_schedules", null, t =>
                        {
                            t.HasComment("График дежурств");
                        });
                });

            modelBuilder.Entity("ScheduleServiceDatabaseImplement.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoreSystemId")
                        .HasColumnType("integer");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CoreSystemId")
                        .IsUnique();

                    b.HasIndex("GroupName");

                    b.ToTable("groups", null, t =>
                        {
                            t.HasComment("Учебные группы");
                        });
                });

            modelBuilder.Entity("ScheduleServiceDatabaseImplement.Models.LessonTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<int>("PairNumber")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("PairNumber")
                        .IsUnique();

                    b.ToTable("lesson_times", null, t =>
                        {
                            t.HasComment("Время учебных пар");
                        });
                });

            modelBuilder.Entity("ScheduleServiceDatabaseImplement.Models.ScheduleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassroomId")
                        .HasColumnType("integer");

                    b.Property<string>("ClassroomNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("interval");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("GroupName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsImported")
                        .HasColumnType("boolean");

                    b.Property<int?>("LessonTimeId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("interval");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<string>("TeacherName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("GroupId");

                    b.HasIndex("LessonTimeId");

                    b.HasIndex("TeacherId");

                    b.ToTable("schedule_items", null, t =>
                        {
                            t.HasComment("Элементы расписания");
                        });
                });

            modelBuilder.Entity("ScheduleServiceDatabaseImplement.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoreSystemId")
                        .HasColumnType("integer");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CoreSystemId")
                        .IsUnique();

                    b.HasIndex("TeacherName");

                    b.ToTable("teachers", null, t =>
                        {
                            t.HasComment("Преподаватели");
                        });
                });

            modelBuilder.Entity("ScheduleServiceDatabaseImplement.Models.DutySchedule", b =>
                {
                    b.HasOne("ScheduleServiceDatabaseImplement.Models.DutyPerson", "DutyPerson")
                        .WithMany("DutySchedules")
                        .HasForeignKey("DutyPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScheduleServiceDatabaseImplement.Models.LessonTime", "LessonTime")
                        .WithMany("DutySchedules")
                        .HasForeignKey("LessonTimeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DutyPerson");

                    b.Navigation("LessonTime");
                });

            modelBuilder.Entity("ScheduleServiceDatabaseImplement.Models.ScheduleItem", b =>
                {
                    b.HasOne("ScheduleServiceDatabaseImplement.Models.Group", "Group")
                        .WithMany("ScheduleItems")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ScheduleServiceDatabaseImplement.Models.LessonTime", "LessonTime")
                        .WithMany("ScheduleItems")
                        .HasForeignKey("LessonTimeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ScheduleServiceDatabaseImplement.Models.Teacher", "Teacher")
                        .WithMany("ScheduleItems")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Group");

                    b.Navigation("LessonTime");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ScheduleServiceDatabaseImplement.Models.DutyPerson", b =>
                {
                    b.Navigation("DutySchedules");
                });

            modelBuilder.Entity("ScheduleServiceDatabaseImplement.Models.Group", b =>
                {
                    b.Navigation("ScheduleItems");
                });

            modelBuilder.Entity("ScheduleServiceDatabaseImplement.Models.LessonTime", b =>
                {
                    b.Navigation("DutySchedules");

                    b.Navigation("ScheduleItems");
                });

            modelBuilder.Entity("ScheduleServiceDatabaseImplement.Models.Teacher", b =>
                {
                    b.Navigation("ScheduleItems");
                });
#pragma warning restore 612, 618
        }
    }
}
