// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.StoragesContracts;
using DepartmentContracts.ViewModels;
using DepartmentDatabaseImplement.Models;

namespace DepartmentDatabaseImplement.Implements
{
    public class StudentOrderBlockStudentStorage : IStudentOrderBlockStudentStorage
    {
        public List<StudentOrderBlockStudentViewModel> GetFullList()
        {
            using var context = new DepartmentDatabase();
            var query = context.Set<StudentOrderBlockStudent>().AsQueryable();
            query = query.Include(x => x.StudentOrderBlock);
            query = query.Include(x => x.Student);
            query = query.Include(x => x.StudentGroupFrom);
            query = query.Include(x => x.StudentGroupTo);
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public List<StudentOrderBlockStudentViewModel> GetFilteredList(StudentOrderBlockStudentSearchModel model)
        {
            using var context = new DepartmentDatabase();
            var query = context.Set<StudentOrderBlockStudent>().AsQueryable();
            query = query.Include(x => x.StudentOrderBlock);
            query = query.Include(x => x.Student);
            query = query.Include(x => x.StudentGroupFrom);
            query = query.Include(x => x.StudentGroupTo);
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public StudentOrderBlockStudentViewModel? GetElement(StudentOrderBlockStudentSearchModel model)
        {
            if (model == null) return null;
            using var context = new DepartmentDatabase();
            var query = context.Set<StudentOrderBlockStudent>().AsQueryable();
            query = query.Include(x => x.StudentOrderBlock);
            query = query.Include(x => x.Student);
            query = query.Include(x => x.StudentGroupFrom);
            query = query.Include(x => x.StudentGroupTo);
            return query
                .FirstOrDefault(x => (model.Id.HasValue && x.Id == model.Id))
                is null ? null : MapToViewModel(query.FirstOrDefault(x => (model.Id.HasValue && x.Id == model.Id))!);
        }

        public StudentOrderBlockStudentViewModel? Insert(StudentOrderBlockStudentBindingModel model)
        {
            var newElement = StudentOrderBlockStudent.Create(model);
            if (newElement == null) return null;
            using var context = new DepartmentDatabase();
            context.Set<StudentOrderBlockStudent>().Add(newElement);
            context.SaveChanges();
            var saved = context.Set<StudentOrderBlockStudent>()
                .Include(x => x.StudentOrderBlock)
                .Include(x => x.Student)
                .Include(x => x.StudentGroupFrom)
                .Include(x => x.StudentGroupTo)
                .FirstOrDefault(x => x.Id == newElement.Id);
            return saved == null ? null : MapToViewModel(saved);
        }

        public StudentOrderBlockStudentViewModel? Update(StudentOrderBlockStudentBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<StudentOrderBlockStudent>().AsQueryable();
            element = element.Include(x => x.StudentOrderBlock);
            element = element.Include(x => x.Student);
            element = element.Include(x => x.StudentGroupFrom);
            element = element.Include(x => x.StudentGroupTo);
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            dbElement.Update(model);
            context.SaveChanges();
            context.Entry(dbElement).Reload();
            context.Entry(dbElement).Reference(x => x.StudentOrderBlock).Load();
            context.Entry(dbElement).Reference(x => x.Student).Load();
            context.Entry(dbElement).Reference(x => x.StudentGroupFrom).Load();
            context.Entry(dbElement).Reference(x => x.StudentGroupTo).Load();
            return MapToViewModel(dbElement);
        }

        public StudentOrderBlockStudentViewModel? Delete(StudentOrderBlockStudentBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<StudentOrderBlockStudent>().AsQueryable();
            element = element.Include(x => x.StudentOrderBlock);
            element = element.Include(x => x.Student);
            element = element.Include(x => x.StudentGroupFrom);
            element = element.Include(x => x.StudentGroupTo);
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            context.Set<StudentOrderBlockStudent>().Remove(dbElement);
            context.SaveChanges();
            return MapToViewModel(dbElement);
        }

        private static StudentOrderBlockStudentViewModel MapToViewModel(StudentOrderBlockStudent entity)
        {
            var vm = entity.GetViewModel;

            vm.StudentOrderBlock = entity.StudentOrderBlock == null
                ? string.Empty
                : entity.StudentOrderBlock.StudentOrderType.ToString();

            vm.Student = entity.Student == null
                ? string.Empty
                : $"{entity.Student.LastName} {entity.Student.FirstName} {entity.Student.Patronymic}".Trim();

            vm.StudentGroupFrom = entity.StudentGroupFrom == null
                ? string.Empty
                : entity.StudentGroupFrom.GroupName;

            vm.StudentGroupTo = entity.StudentGroupTo == null
                ? string.Empty
                : entity.StudentGroupTo.GroupName;

            return vm;
        }

        public List<StudentMovementHistoryViewModel> GetStudentMovementHistory(int studentId)
        {
            using var context = new DepartmentDatabase();

            var query = context.Set<StudentOrderBlockStudent>()
                .Include(x => x.StudentOrderBlock)
                    .ThenInclude(x => x.StudentOrder)
                .Include(x => x.StudentGroupFrom)
                .Include(x => x.StudentGroupTo)
                .Where(x => x.StudentId == studentId);

            return query
                .ToList()
                .Select(x => new StudentMovementHistoryViewModel
                {
                    StudentOrderId = x.StudentOrderBlock.StudentOrderId,
                    StudentOrderBlockId = x.StudentOrderBlockId,
                    StudentOrderBlockStudentId = x.Id,

                    OrderNumber = x.StudentOrderBlock.StudentOrder == null
                        ? string.Empty
                        : x.StudentOrderBlock.StudentOrder.OrderNumber,

                    OrderDate = x.StudentOrderBlock.StudentOrder == null
                        ? DateTime.MinValue
                        : x.StudentOrderBlock.StudentOrder.OrderDate,

                    StudentOrderType = x.StudentOrderBlock.StudentOrderType,

                    StudentGroupFromId = x.StudentGroupFromId,
                    StudentGroupFromName = x.StudentGroupFrom == null
                        ? null
                        : x.StudentGroupFrom.GroupName,

                    StudentGroupToId = x.StudentGroupToId,
                    StudentGroupToName = x.StudentGroupTo == null
                        ? null
                        : x.StudentGroupTo.GroupName,

                    MovementDescription = BuildMovementDescription(
                        x.StudentOrderBlock.StudentOrderType,
                        x.StudentGroupFrom == null ? null : x.StudentGroupFrom.GroupName,
                        x.StudentGroupTo == null ? null : x.StudentGroupTo.GroupName)
                })
                .OrderBy(x => x.OrderDate)
                .ThenBy(x => x.StudentOrderBlockStudentId)
                .ToList();
        }

        private static string BuildMovementDescription(
            DepartmentDataModels.Enums.StudentOrderType orderType,
            string? groupFrom,
            string? groupTo)
        {
            var from = string.IsNullOrWhiteSpace(groupFrom) ? "—" : groupFrom;
            var to = string.IsNullOrWhiteSpace(groupTo) ? "—" : groupTo;

            return orderType.ToString() switch
            {
                "Зачисление" => $"Зачисление в группу {to}",
                "Отчисление" => $"Отчисление из группы {from}",
                "Перевод" => $"Перевод из группы {from} в группу {to}",
                "Академ" => $"Академический отпуск, группа {from}",
                _ => orderType.ToString()
            };
        }
    }
}
