// <auto-generated />

using System;
using DepartmentDataModels.Enums;
using DepartmentDataModels.Models;
using DepartmentContracts.Attributes;

namespace DepartmentContracts.ViewModels
{
    public class DisciplineStudentRecordViewModel : IDisciplineStudentRecordModel
    {
        [Column(visible: false)]
        public int Id { get; set; }

        [Column(visible: false)]
        public int DisciplineId { get; set; }

        [Column(title: "", width: 100)]
        public string Discipline { get; set; } = string.Empty;

        [Column(visible: false)]
        public int StudentId { get; set; }

        [Column(title: "", width: 100)]
        public string Student { get; set; } = string.Empty;

        [Column(title: "", width: 100)]
        public Semesters Semester { get; set; }

        [Column(title: "", width: 100)]
        public string Variant { get; set; } = string.Empty;

        [Column(title: "", width: 100)]
        public int SubGroup { get; set; }

        [Column(title: "", width: 100)]
        public MarkType MarkType { get; set; }

        [Column(title: "Дата оценки", width: 120)]
        public DateTime? MarkDate { get; set; }
    }
}