// <auto-generated />
using System;
using DepartmentDatabaseImplement;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DepartmentDatabaseImplement.Migrations
{
    [DbContext(typeof(DepartmentDatabase))]
    [Migration("20260511192041_AddSystemAuthorization")]
    partial class AddSystemAuthorization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.AcademicPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicCourses")
                        .HasColumnType("integer");

                    b.Property<int?>("EducationDirectionId")
                        .HasColumnType("integer");

                    b.Property<int>("EducationForm")
                        .HasColumnType("integer");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EducationDirectionId");

                    b.ToTable("AcademicPlans");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.AcademicPlanRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicHours")
                        .HasColumnType("integer");

                    b.Property<int>("AcademicPlanId")
                        .HasColumnType("integer");

                    b.Property<int?>("AcademicPlanRecordParentId")
                        .HasColumnType("integer");

                    b.Property<int?>("CourseProject")
                        .HasColumnType("integer");

                    b.Property<int?>("CourseWork")
                        .HasColumnType("integer");

                    b.Property<int?>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<int?>("Exam")
                        .HasColumnType("integer");

                    b.Property<int?>("GradedPass")
                        .HasColumnType("integer");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LaboratoryHours")
                        .HasColumnType("integer");

                    b.Property<int?>("Lectures")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Pass")
                        .HasColumnType("integer");

                    b.Property<int?>("PracticalHours")
                        .HasColumnType("integer");

                    b.Property<int?>("Rgr")
                        .HasColumnType("integer");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.Property<int>("Zet")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AcademicPlanId");

                    b.HasIndex("AcademicPlanRecordParentId");

                    b.HasIndex("DisciplineId");

                    b.ToTable("AcademicPlanRecords");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<bool>("HasProjector")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotUseInSchedule")
                        .HasColumnType("boolean");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.Discipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisciplineBlockBlueAsteriskName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisciplineBlockId")
                        .HasColumnType("integer");

                    b.Property<string>("DisciplineDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisciplineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisciplineShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasCourseProject")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasCourseWork")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasCredit")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasExam")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineBlockId");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.DisciplineBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisciplineBlockBlueAsteriskName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisciplineBlockOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("DisciplineBlockUseForGrouping")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DisciplineBlocks");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.DisciplineStudentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<int>("MarkType")
                        .HasColumnType("integer");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("SubGroup")
                        .HasColumnType("integer");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("StudentId");

                    b.ToTable("DisciplineStudentRecords");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.EducationDirection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cipher")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Qualification")
                        .HasColumnType("integer");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EducationDirections");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.Lecturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomeNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LecturerDepartmentPostId")
                        .HasColumnType("integer");

                    b.Property<int?>("LecturerStudyPostId")
                        .HasColumnType("integer");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OnlyForPrivate")
                        .HasColumnType("boolean");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("Rank2")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LecturerDepartmentPostId");

                    b.HasIndex("LecturerStudyPostId");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.LecturerDepartmentPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentPostTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("LecturerDepartmentPosts");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.LecturerStudyPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Hours")
                        .HasColumnType("integer");

                    b.Property<string>("StudyPostTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LecturerStudyPosts");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSteward")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumberOfBook")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea");

                    b.Property<int?>("StudentGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentState")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentGroupId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.StudentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Course")
                        .HasColumnType("integer");

                    b.Property<int?>("CuratorId")
                        .HasColumnType("integer");

                    b.Property<int>("EducationDirectionId")
                        .HasColumnType("integer");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CuratorId");

                    b.HasIndex("EducationDirectionId");

                    b.ToTable("StudentGroups");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.StudentOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentOrderType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("StudentOrders");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.StudentOrderBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EducationDirectionId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentOrderId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentOrderType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EducationDirectionId");

                    b.HasIndex("StudentOrderId");

                    b.ToTable("StudentOrderBlocks");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.StudentOrderBlockStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("StudentGroupFromId")
                        .HasColumnType("integer");

                    b.Property<int?>("StudentGroupToId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentOrderBlockId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentGroupFromId");

                    b.HasIndex("StudentGroupToId");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentOrderBlockId");

                    b.ToTable("StudentOrderBlockStudents");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.SystemPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SystemPermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Core.Access",
                            Name = "Доступ к основному модулю"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Load.Access",
                            Name = "Доступ к модулю расчета нагрузки"
                        },
                        new
                        {
                            Id = 3,
                            Code = "Lab.Inventory.Access",
                            Name = "Доступ к МОЛ"
                        },
                        new
                        {
                            Id = 4,
                            Code = "Lab.DutySchedule.Access",
                            Name = "Доступ к графику дежурств"
                        },
                        new
                        {
                            Id = 5,
                            Code = "Lab.Schedule.View",
                            Name = "Просмотр расписания"
                        },
                        new
                        {
                            Id = 6,
                            Code = "Lab.Schedule.BookConsultation",
                            Name = "Добавление консультаций"
                        });
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.SystemRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SystemRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "LabHead",
                            Name = "Зав. лабораторией"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Admin",
                            Name = "Администратор"
                        },
                        new
                        {
                            Id = 3,
                            Code = "DepartmentHead",
                            Name = "Зав. кафедрой"
                        },
                        new
                        {
                            Id = 4,
                            Code = "Teacher",
                            Name = "Преподаватель"
                        },
                        new
                        {
                            Id = 5,
                            Code = "Developer",
                            Name = "Разработчик"
                        });
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.SystemRolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("SystemRolePermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            PermissionId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            PermissionId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 5,
                            PermissionId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 6,
                            PermissionId = 2,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 7,
                            PermissionId = 4,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 8,
                            PermissionId = 6,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 9,
                            PermissionId = 6,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 10,
                            PermissionId = 1,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 11,
                            PermissionId = 2,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 12,
                            PermissionId = 3,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 13,
                            PermissionId = 4,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 14,
                            PermissionId = 5,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 15,
                            PermissionId = 6,
                            RoleId = 5
                        });
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.SystemUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("SystemUsers");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.SystemUserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("SystemUserRoles");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.AcademicPlan", b =>
                {
                    b.HasOne("DepartmentDatabaseImplement.Models.EducationDirection", "EducationDirection")
                        .WithMany("AcademicPlans")
                        .HasForeignKey("EducationDirectionId");

                    b.Navigation("EducationDirection");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.AcademicPlanRecord", b =>
                {
                    b.HasOne("DepartmentDatabaseImplement.Models.AcademicPlan", "AcademicPlan")
                        .WithMany("AcademicPlanRecords")
                        .HasForeignKey("AcademicPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DepartmentDatabaseImplement.Models.AcademicPlanRecord", null)
                        .WithMany("AcademicPlanRecords")
                        .HasForeignKey("AcademicPlanRecordParentId");

                    b.HasOne("DepartmentDatabaseImplement.Models.Discipline", "Discipline")
                        .WithMany("AcademicPlanRecords")
                        .HasForeignKey("DisciplineId");

                    b.Navigation("AcademicPlan");

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.Discipline", b =>
                {
                    b.HasOne("DepartmentDatabaseImplement.Models.DisciplineBlock", "DisciplineBlock")
                        .WithMany("Disciplines")
                        .HasForeignKey("DisciplineBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DisciplineBlock");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.DisciplineStudentRecord", b =>
                {
                    b.HasOne("DepartmentDatabaseImplement.Models.Discipline", "Discipline")
                        .WithMany("DisciplineStudentRecords")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DepartmentDatabaseImplement.Models.Student", "Student")
                        .WithMany("DisciplineStudentRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.Lecturer", b =>
                {
                    b.HasOne("DepartmentDatabaseImplement.Models.LecturerDepartmentPost", "LecturerDepartmentPost")
                        .WithMany("Lecturers")
                        .HasForeignKey("LecturerDepartmentPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DepartmentDatabaseImplement.Models.LecturerStudyPost", "LecturerStudyPost")
                        .WithMany("Lecturers")
                        .HasForeignKey("LecturerStudyPostId");

                    b.Navigation("LecturerDepartmentPost");

                    b.Navigation("LecturerStudyPost");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.Student", b =>
                {
                    b.HasOne("DepartmentDatabaseImplement.Models.StudentGroup", "StudentGroup")
                        .WithMany("Students")
                        .HasForeignKey("StudentGroupId");

                    b.Navigation("StudentGroup");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.StudentGroup", b =>
                {
                    b.HasOne("DepartmentDatabaseImplement.Models.Lecturer", "Curator")
                        .WithMany()
                        .HasForeignKey("CuratorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DepartmentDatabaseImplement.Models.EducationDirection", "EducationDirection")
                        .WithMany("StudentGroups")
                        .HasForeignKey("EducationDirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curator");

                    b.Navigation("EducationDirection");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.StudentOrderBlock", b =>
                {
                    b.HasOne("DepartmentDatabaseImplement.Models.EducationDirection", "EducationDirection")
                        .WithMany("StudentOrderBlocks")
                        .HasForeignKey("EducationDirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DepartmentDatabaseImplement.Models.StudentOrder", "StudentOrder")
                        .WithMany("StudentOrderBlocks")
                        .HasForeignKey("StudentOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationDirection");

                    b.Navigation("StudentOrder");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.StudentOrderBlockStudent", b =>
                {
                    b.HasOne("DepartmentDatabaseImplement.Models.StudentGroup", "StudentGroupFrom")
                        .WithMany("StudentFromOrderBlockStudents")
                        .HasForeignKey("StudentGroupFromId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DepartmentDatabaseImplement.Models.StudentGroup", "StudentGroupTo")
                        .WithMany("StudentToOrderBlockStudents")
                        .HasForeignKey("StudentGroupToId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DepartmentDatabaseImplement.Models.Student", "Student")
                        .WithMany("StudentOrderBlockStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DepartmentDatabaseImplement.Models.StudentOrderBlock", "StudentOrderBlock")
                        .WithMany("StudentOrderBlockStudents")
                        .HasForeignKey("StudentOrderBlockId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("StudentGroupFrom");

                    b.Navigation("StudentGroupTo");

                    b.Navigation("StudentOrderBlock");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.SystemRolePermission", b =>
                {
                    b.HasOne("DepartmentDatabaseImplement.Models.SystemPermission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DepartmentDatabaseImplement.Models.SystemRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.SystemUserRole", b =>
                {
                    b.HasOne("DepartmentDatabaseImplement.Models.SystemRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DepartmentDatabaseImplement.Models.SystemUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.AcademicPlan", b =>
                {
                    b.Navigation("AcademicPlanRecords");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.AcademicPlanRecord", b =>
                {
                    b.Navigation("AcademicPlanRecords");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.Discipline", b =>
                {
                    b.Navigation("AcademicPlanRecords");

                    b.Navigation("DisciplineStudentRecords");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.DisciplineBlock", b =>
                {
                    b.Navigation("Disciplines");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.EducationDirection", b =>
                {
                    b.Navigation("AcademicPlans");

                    b.Navigation("StudentGroups");

                    b.Navigation("StudentOrderBlocks");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.LecturerDepartmentPost", b =>
                {
                    b.Navigation("Lecturers");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.LecturerStudyPost", b =>
                {
                    b.Navigation("Lecturers");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.Student", b =>
                {
                    b.Navigation("DisciplineStudentRecords");

                    b.Navigation("StudentOrderBlockStudents");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.StudentGroup", b =>
                {
                    b.Navigation("StudentFromOrderBlockStudents");

                    b.Navigation("StudentToOrderBlockStudents");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.StudentOrder", b =>
                {
                    b.Navigation("StudentOrderBlocks");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.StudentOrderBlock", b =>
                {
                    b.Navigation("StudentOrderBlockStudents");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.SystemPermission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.SystemRole", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.SystemUser", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
